Bringing master up to date to 2019 02 01
kinecosystem/kin-website-docs pull request #1
Opened 2019-02-01 23:35 UTC by andreaKin

Imported all changes Kevin and I made to the documentation up to 2019 02 01.

2019-02-03 05:11 UTC, cnotethegr8 requested changes

2019-02-03 05:11 UTC, cnotethegr8 commented on website/siteConfig.js
> +  organizationName: 'Kin',
fyi, this needs to be `kinecosystem` for github pages

2019-02-03 07:28 UTC, cnotethegr8 approved these changes

2019-02-04 23:24 UTC, andreaKin commented on website/siteConfig.js
> +  organizationName: 'Kin',
Got it.

2019-02-05 17:34 UTC, merged