Added the bootstrap documentation
kinecosystem/kin-website-docs pull request #58
Opened 2019-08-29 12:18 UTC by ravitb

2019-08-29 13:31 UTC, chaseeb reviewed
Do you think it would be beneficial for these docs to tell the options for:

- Horizon_Endpoint
- Network_Passphrase
- Network_Name

Also I do not think it's completely clear to someone how to actually run this server on somewhere like heroku or AWS.  Do we think it might be helpful?  Someone that wants to use the bootstrap is mostly likely doing so because they are unfamiliar with building a node app.  Which also means they are probably unfamiliar with deploying a docker on a server.  It seems like we could provide additional information on the expectations.

2019-09-01 08:26 UTC, yosriz commented on website/sidebars.json
> +      "python/bootstrap"
wrong path

2019-09-01 08:32 UTC, yosriz commented on docs/nodejs/bootstrap.md
> +```bash
must we clone the repo, right? if so, add this step.
In general, I think we need here 0 to 1 steps including how to generate a seed, and default values inside the docker-compose for reference. the idea is to have dead-simple instruction in one place.
I understand that it's borrowed from python bootstrap, so adding also @Ronserruya to get his input.

2019-09-01 14:36 UTC, yosriz commented on docs/nodejs/bootstrap.md
> +The server can be configured from the docker-compose.yml file.
fix to .env file, include it in the steps instructions. (see next comment)

2019-09-01 14:36 UTC, yosriz requested changes
see comments

2020-03-30 19:41 UTC, mrsegev approved these changes

2021-06-26 01:26 UTC, closed without merging